<?php

namespace BootstrapDemoBundle\Repository;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{
	public function loadUserByUsername($username_or_email)
	{
		$user = $this->createQueryBuilder('u')
		->where('u.username = :username OR u.email = :email')
		->setParameter('username', $username_or_email)
		->setParameter('email', $username_or_email)
		->getQuery()
		->getOneOrNullResult();
	
		if (null === $user) {
			$message = sprintf(
					'Unable to find an active admin BootstrapDemoBundle:User object identified by "%s".',
					$username_or_email
					);
			throw new UsernameNotFoundException($message);
		}
	
		return $user;
	}
}
